"""Shared autofill orchestration: CLI entry point and browser pipeline."""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from collections.abc import Callable
from datetime import UTC, datetime
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from application_submit_common import (
    PROJECT_ROOT,
    build_email_confirmation_watcher,
    clear_pending_user_input,
    default_answer_provider,
    find_output_dir,
    json_dumps_pretty,
    reply_to_confirmation_email,
    sync_notion_after_submit,
    write_pending_user_input_for_unconfirmed_fields,
    write_submission_result,
)

# Exit code returned when submission is blocked by a captcha.
# submit_application.py checks for this code and records a graceful skip.
CAPTCHA_SKIP_EXIT_CODE = 75
MAX_VALIDATION_RETRIES = 2
from autofill_common import (
    blocking_unconfirmed_report_entries,
    board_file_constants,
    capture_full_page,
    clear_current_attempt_artifacts,
    click_submit_button,
    detect_live_required_unfilled_fields,
    fill_basic_step,
    is_visible_confirmation_blocker,
    page_snapshot,
    required_artifact_blocker_step,
    simple_board_review_boundary_blocker,
    write_report,
)
from autofill_common import wait_for_captcha_resolution as _default_captcha_wait
from browser_runtime import (
    ensure_google_session,
    launch_chromium_browser,
    submit_browser_profile_dir,
    submit_slow_mo_ms,
    submit_viewport,
)
from llm_provider import VALID_PROVIDERS
from output_layout import role_submit_path
from project_env import load_project_env

load_project_env()

_PRE_FORM_MANUAL_CHALLENGE_PATTERNS = (
    (
        re.compile(r"\baccess is temporarily restricted\b", re.I),
        "Access is temporarily restricted before the application form rendered.",
    ),
    (
        re.compile(r"\bunusual activity from your device or network\b", re.I),
        "The job board blocked the application flow because it detected unusual activity.",
    ),
)
_PRE_FORM_MANUAL_CHALLENGE_HTML_MARKERS = (
    "captcha-delivery.com",
    "geo.captcha-delivery.com",
    "DataDome Device Check",
)
_PRE_FORM_SERVICE_UNAVAILABLE_PATTERNS = (
    (
        re.compile(r"\b403 error\b", re.I),
        "The job board returned a 403 error page before the application form rendered.",
    ),
    (
        re.compile(r"\bthe request could not be satisfied\b", re.I),
        "The job board returned an upstream edge error page before the application form rendered.",
    ),
    (
        re.compile(r"\brequest blocked\b", re.I),
        "The job board blocked access to the application page before the form rendered.",
    ),
)
_PRE_FORM_SERVICE_UNAVAILABLE_HTML_MARKERS = (
    "generated by cloudfront",
    "the request could not be satisfied",
    "request blocked",
)
_PRE_FORM_JOB_CLOSED_PATTERNS = (
    (
        re.compile(r"\bthe job you requested was not found\b", re.I),
        "job_closed: The job board says the posting was not found before the form rendered.",
    ),
    (
        re.compile(r"\bjob not found\b", re.I),
        "job_closed: The job board says the posting was not found before the form rendered.",
    ),
    (
        re.compile(r"\bno longer accepting applications\b", re.I),
        "job_closed: The job board says the posting is no longer accepting applications.",
    ),
    (
        re.compile(r"\bthis job is no longer available\b", re.I),
        "job_closed: The job board says the posting is no longer available.",
    ),
    (
        re.compile(r"\b(?:sorry,\s*)?this position has been filled\b", re.I),
        "job_closed: The job board says the position has been filled.",
    ),
    (
        re.compile(r"\b(?:this\s+)?job is no longer active\b", re.I),
        "job_closed: The job board says the posting is no longer active.",
    ),
)
_PRE_FORM_JOB_CLOSED_HTML_MARKERS = (
    '"organization":null,"posting":null,"jobBoard":null',
    '"organization": null, "posting": null, "jobBoard": null',
)


def _read_current_attempt_submission_result(out_dir: Path) -> dict[str, object] | None:
    result_path = role_submit_path(out_dir, "application_submission_result.json")
    if not result_path.exists():
        return None
    try:
        data = json.loads(result_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    return data if isinstance(data, dict) else None


def _current_attempt_artifact_payload(out_dir: Path, board_name: str) -> dict[str, object]:
    constants = board_file_constants(board_name)
    return {
        "out_dir": str(out_dir),
        "artifacts": {
            "report_markdown": str(role_submit_path(out_dir, constants["report_md"])),
            "report_json": str(role_submit_path(out_dir, constants["report_json"])),
            "pre_submit_screenshot": str(role_submit_path(out_dir, constants["pre_submit_screenshot"])),
            "post_submit_screenshot": str(role_submit_path(out_dir, constants["post_submit_screenshot"])),
            "submit_debug_html": str(role_submit_path(out_dir, constants["submit_debug_html"])),
            "submit_debug_screenshot": str(role_submit_path(out_dir, constants["submit_debug_screenshot"])),
            "payload_json": str(role_submit_path(out_dir, constants["payload_json"])),
            "page_screenshots_dir": str(role_submit_path(out_dir, constants["page_screenshots_dir"])),
        },
    }


def _page_content_fragments(page) -> list[str]:
    fragments: list[str] = []

    def append_fragment(value: str | None) -> None:
        text = str(value or "").strip()
        if text:
            fragments.append(text)

    def read_context(context) -> None:
        try:
            body = context.locator("body")
            if body.count():
                append_fragment(body.inner_text(timeout=1000))
        except Exception:
            pass
        try:
            append_fragment(context.content())
        except Exception:
            pass

    read_context(page)
    raw_frames = getattr(page, "frames", None)
    if callable(raw_frames):
        try:
            frames = list(raw_frames())
        except Exception:
            frames = []
    else:
        frames = list(raw_frames or [])
    for frame in frames:
        if frame is page:
            continue
        read_context(frame)
    return fragments


def _pre_form_manual_challenge(page) -> dict[str, str] | None:
    url = ""
    try:
        url = str(page.url or "")
    except Exception:
        pass

    combined = "\n".join(_page_content_fragments(page)).strip()
    for pattern, message in _PRE_FORM_MANUAL_CHALLENGE_PATTERNS:
        if pattern.search(combined):
            return {"reason": "manual_challenge", "message": message, "url": url}

    combined_lower = combined.casefold()
    for marker in _PRE_FORM_MANUAL_CHALLENGE_HTML_MARKERS:
        if marker.casefold() in combined_lower:
            return {
                "reason": "manual_challenge",
                "message": "The job board presented a pre-form anti-bot challenge instead of the application form.",
                "url": url,
            }
    return None


def _pre_form_service_unavailable(page) -> dict[str, str] | None:
    combined = "\n".join(_page_content_fragments(page)).casefold()
    if not combined:
        return None
    if any(marker in combined for marker in _PRE_FORM_SERVICE_UNAVAILABLE_HTML_MARKERS):
        return {"message": "The job board appears to be temporarily unavailable or access-blocked upstream."}
    for pattern, message in _PRE_FORM_SERVICE_UNAVAILABLE_PATTERNS:
        if pattern.search(combined):
            return {"message": message}
    return None


def _pre_form_job_closed(page) -> dict[str, str] | None:
    combined = "\n".join(_page_content_fragments(page))
    if not combined:
        return None
    for marker in _PRE_FORM_JOB_CLOSED_HTML_MARKERS:
        if marker in combined:
            return {"message": "job_closed: The application page resolved to an unavailable job shell."}
    for pattern, message in _PRE_FORM_JOB_CLOSED_PATTERNS:
        if pattern.search(combined):
            return {"message": message}
    return None


def _handle_pre_form_terminal_state(
    *,
    page,
    payload: dict,
    board_title: str,
    capture_fn: Callable,
) -> int | None:
    manual_challenge = _pre_form_manual_challenge(page)
    job_closed = None if manual_challenge is not None else _pre_form_job_closed(page)
    service_unavailable = (
        None if manual_challenge is not None or job_closed is not None else _pre_form_service_unavailable(page)
    )
    if manual_challenge is None and job_closed is None and service_unavailable is None:
        return None

    debug_html = Path(payload["artifacts"]["submit_debug_html"])
    debug_png = Path(payload["artifacts"]["submit_debug_screenshot"])
    try:
        debug_html.write_text(page.content(), encoding="utf-8")
    except Exception:
        pass
    try:
        capture_fn(page, debug_png)
    except Exception:
        pass
    if manual_challenge is not None:
        print(
            f"{board_title} captcha required before the application form rendered. "
            f"{manual_challenge['message']} "
            f"See {debug_html.relative_to(PROJECT_ROOT)} and {debug_png.relative_to(PROJECT_ROOT)}.",
            file=sys.stderr,
        )
        return CAPTCHA_SKIP_EXIT_CODE

    if job_closed is not None:
        write_submission_result(
            out_dir=Path(payload["out_dir"]),
            status="job_closed",
            failure_type="job_closed",
            job_url=str(payload.get("job_url") or ""),
            message=job_closed["message"],
            board=board_title.casefold(),
            provider=str(payload.get("provider") or "").strip() or None,
            artifacts={
                "submit_debug_html": str(debug_html),
                "submit_debug_screenshot": str(debug_png),
            },
        )
        print(
            f"{board_title} did not reach the application form. {job_closed['message']} "
            f"See {debug_html.relative_to(PROJECT_ROOT)} and {debug_png.relative_to(PROJECT_ROOT)}.",
            file=sys.stderr,
        )
        return 1

    write_submission_result(
        out_dir=Path(payload["out_dir"]),
        status="service_unavailable",
        failure_type="service_unavailable",
        job_url=str(payload.get("job_url") or ""),
        message=(
            f"{board_title} did not reach the application form because the site returned an upstream "
            f"error or access block before the form rendered."
        ),
        board=board_title.casefold(),
        provider=str(payload.get("provider") or "").strip() or None,
        artifacts={
            "submit_debug_html": str(debug_html),
            "submit_debug_screenshot": str(debug_png),
        },
    )
    print(
        f"{board_title} did not reach the application form. {service_unavailable['message']} "
        f"See {debug_html.relative_to(PROJECT_ROOT)} and {debug_png.relative_to(PROJECT_ROOT)}.",
        file=sys.stderr,
    )
    return 1


def _handle_pre_form_timeout(
    *,
    page,
    payload: dict,
    board_title: str,
    capture_fn: Callable,
) -> int | None:
    return _handle_pre_form_terminal_state(
        page=page,
        payload=payload,
        board_title=board_title,
        capture_fn=capture_fn,
    )


def autofill_main(
    board_name: str,
    build_payload_fn: Callable[[Path, str], dict],
    *,
    has_browser: bool = True,
    run_browser_fn: Callable[[Path, bool, bool], int] | None = None,
) -> int:
    """Shared CLI entry point for all autofill scripts."""
    board_title = board_name.capitalize()
    parser = argparse.ArgumentParser(description=f"Autofill a {board_title} application using existing job assets.")
    parser.add_argument(
        "target",
        help="Output directory (e.g. output/company/role-slug) or a job URL.",
    )
    parser.add_argument(
        "--payload-only",
        action="store_true",
        help=f"Only generate {board_name}_autofill_payload.json.",
    )
    parser.add_argument(
        "--headless",
        action="store_true",
        help="Launch the Playwright runtime in headless mode.",
    )
    submit_group = parser.add_mutually_exclusive_group()
    submit_group.add_argument(
        "--submit",
        action="store_true",
        help="Submit the application after autofill.",
    )
    submit_group.add_argument(
        "--draft",
        action="store_true",
        help="Fill the form and take screenshots but stop before submitting.",
    )
    parser.add_argument(
        "--browser-provider",
        choices=("local", "steel"),
        default=None,
        help="Browser runtime (default: env or local).",
    )
    parser.add_argument(
        "--provider",
        choices=VALID_PROVIDERS,
        default=None,
        help="LLM provider for generated answers.",
    )
    args = parser.parse_args()

    out_dir = find_output_dir(args.target)
    if args.browser_provider:
        os.environ["JOB_ASSETS_BROWSER_PROVIDER"] = args.browser_provider
    if args.provider:
        os.environ["ASSET_LLM_PROVIDER"] = args.provider

    provider = args.provider or default_answer_provider()
    clear_current_attempt_artifacts(_current_attempt_artifact_payload(out_dir, board_name))
    payload = build_payload_fn(out_dir, provider)
    if "steps" in payload:
        write_report(payload, board_name=board_name)

    constants = board_file_constants(board_name)
    payload_path = role_submit_path(out_dir, constants["payload_json"])
    payload_path.parent.mkdir(parents=True, exist_ok=True)
    payload_path.write_text(json_dumps_pretty(payload) + "\n", encoding="utf-8")
    print(f"Wrote {payload_path.relative_to(PROJECT_ROOT)}")

    if args.payload_only:
        return 0

    if not has_browser or run_browser_fn is None:
        return 0

    submit = args.submit and not args.draft
    return run_browser_fn(payload_path, args.headless, submit)


def run_simple_board_pipeline(
    payload_path: Path,
    *,
    headless: bool,
    submit: bool,
    board_name: str,
    form_selector: str,
    submit_button_names: tuple[str, ...] | list[str],
    classify_state_fn,
    fill_step_fn=fill_basic_step,
    preferred_capture_selectors: tuple[str, ...] = (),
    captcha_type: str = "recaptcha",
    form_ready_selector: str | None = None,
    form_ready_fn=None,
    pre_submit_hook=None,
    post_navigate_hook=None,
    post_fill_hook=None,
    confirmed_outcome_from_email_fn=None,
) -> int:
    return run_browser_pipeline(
        payload_path,
        headless=headless,
        submit=submit,
        board_name=board_name,
        retry_unconfirmed_visible_self_id_once=False,
        form_ready_selector=form_ready_selector or "body",
        form_ready_fn=form_ready_fn,
        fill_step_fn=fill_step_fn,
        page_snapshot_fn=lambda page: page_snapshot(page, form_selector=form_selector, captcha_type=captcha_type),
        classify_state_fn=classify_state_fn,
        click_submit_fn=lambda page: click_submit_button(page, button_names=submit_button_names),
        capture_fn=lambda page, path: capture_full_page(
            page,
            path,
            preferred_selectors=preferred_capture_selectors,
        ),
        live_required_field_scan_fn=lambda page, steps: detect_live_required_unfilled_fields(page, steps=steps),
        draft_boundary_scan_fn=simple_board_review_boundary_blocker,
        pre_submit_hook=pre_submit_hook,
        post_navigate_hook=post_navigate_hook,
        post_fill_hook=post_fill_hook,
        confirmed_outcome_from_email_fn=confirmed_outcome_from_email_fn,
    )


def run_browser_pipeline(
    payload_path: Path,
    *,
    headless: bool,
    submit: bool,
    board_name: str,
    retry_unconfirmed_visible_self_id_once: bool = False,
    form_ready_selector: str | None = None,
    form_ready_fn: Callable | None = None,
    fill_step_fn: Callable,
    page_snapshot_fn: Callable,
    classify_state_fn: Callable,
    click_submit_fn: Callable,
    capture_fn: Callable,
    live_required_field_scan_fn: Callable | None = None,
    draft_boundary_scan_fn: Callable | None = None,
    pre_submit_hook: Callable | None = None,
    post_navigate_hook: Callable | None = None,
    post_fill_hook: Callable | None = None,
    confirmed_outcome_from_email_fn: Callable | None = None,
) -> int:
    try:
        from playwright.sync_api import TimeoutError as PlaywrightTimeoutError
        from playwright.sync_api import sync_playwright
    except ImportError:
        print("ERROR: Playwright is not installed.", file=sys.stderr)
        return 1

    board_title = board_name.capitalize()
    payload = json.loads(payload_path.read_text(encoding="utf-8"))
    out_dir = Path(payload["out_dir"])
    # Payload build already cleared stale submit state and rewrote fresh answer artifacts.
    # Preserve those answer/verification sidecars here while refreshing browser-phase proof.
    clear_current_attempt_artifacts(payload, preserve_answer_artifacts=True)
    page_screenshots_dir = Path(payload["artifacts"]["page_screenshots_dir"])
    page_screenshots_dir.mkdir(parents=True, exist_ok=True)

    with sync_playwright() as playwright:
        viewport = submit_viewport()
        browser = launch_chromium_browser(
            playwright,
            headless=headless,
            slow_mo=submit_slow_mo_ms(headless),
            channel_env_var="JOB_ASSETS_SUBMIT_BROWSER_CHANNEL",
            executable_env_var="JOB_ASSETS_SUBMIT_BROWSER_EXECUTABLE",
            persistent_profile_dir=submit_browser_profile_dir(),
            prefer_local_browser=True,
            viewport=viewport,
            device_scale_factor=2,
            purpose=f"{board_title} autofill",
        )
        page = browser.new_page(viewport=viewport, device_scale_factor=2)
        try:
            # --- Phase 0: Ensure Google session for reCAPTCHA ---
            ensure_google_session(page, headless=headless)

            # --- Phase 1: Navigate and wait for form ---
            # Minimize browser window immediately so it doesn't steal focus.
            # reveal_manual_challenge() will un-minimize when user action is needed.
            if not headless:
                from browser_runtime import minimize_browser_window

                page.wait_for_timeout(500)  # let window render before minimizing
                minimize_browser_window(page)
            try:
                navigate_url = str(payload.get("application_url") or payload["job_url"])
                page.goto(navigate_url, wait_until="domcontentloaded", timeout=30000)
                if form_ready_fn is not None:
                    form_ready_fn(page)
                elif form_ready_selector is not None:
                    page.wait_for_selector(form_ready_selector, timeout=25000)
                page.wait_for_timeout(1000)
                if post_navigate_hook is not None:
                    post_navigate_hook(page)
                    # Re-read payload in case the hook injected new steps
                    payload = json.loads(payload_path.read_text(encoding="utf-8"))
            except PlaywrightTimeoutError:
                handled_rc = _handle_pre_form_timeout(
                    page=page,
                    payload=payload,
                    board_title=board_title,
                    capture_fn=capture_fn,
                )
                if handled_rc is not None:
                    return handled_rc
                raise

            current_attempt_result = _read_current_attempt_submission_result(out_dir)
            if current_attempt_result is not None:
                clear_pending_user_input(out_dir)
                pre_submit_path = Path(payload["artifacts"]["pre_submit_screenshot"])
                capture_fn(page, pre_submit_path)
                if not pre_submit_path.exists():
                    capture_fn(page, pre_submit_path)
                page_path = page_screenshots_dir / "page_01.png"
                capture_fn(page, page_path)
                if not page_path.exists():
                    capture_fn(page, page_path)
                message = str(current_attempt_result.get("message") or "").strip()
                if message:
                    print(message, file=sys.stderr)
                return 1 if submit else 0

            handled_rc = _handle_pre_form_terminal_state(
                page=page,
                payload=payload,
                board_title=board_title,
                capture_fn=capture_fn,
            )
            if handled_rc is not None:
                return handled_rc

            # --- Phase 2: Fill form fields ---
            steps = [dict(step) for step in payload["steps"]]
            for step in steps:
                fill_step_fn(page, step)
                page.wait_for_timeout(100)

            # --- Phase 2b: Verify text fields ---
            # React controlled forms may lose textarea values when subsequent
            # choice/button fills trigger re-renders.  Re-fill any empty
            # required text fields after the initial pass.
            for step in steps:
                if not step.get("filled"):
                    continue
                if step.get("kind") not in ("text", "textarea"):
                    continue
                field_type = step.get("field_type", "")
                value = str(step.get("value", ""))
                if field_type not in ("LongText",) and len(value) < 400:
                    continue
                path = step.get("path", "")
                if not path:
                    continue
                for sel in (f'textarea[name="{path}"]', f'textarea[id="{path}"]'):
                    loc = page.locator(sel).first
                    if loc.count():
                        try:
                            loc.scroll_into_view_if_needed(timeout=2000)
                            actual = (loc.input_value() or "").strip()
                            if not actual:
                                loc.click()
                                loc.fill(value)
                        except Exception:
                            pass
                        break

            # --- Phase 2c: Retry visible confirmation blockers once ---
            if retry_unconfirmed_visible_self_id_once:
                retry_candidates = [
                    step
                    for step in steps
                    if is_visible_confirmation_blocker(step)
                    and not step.get("filled")
                    and str(step.get("status") or "").strip().casefold() != "skipped_not_found"
                ]
                for step in retry_candidates:
                    step["confirmation_retry_attempted"] = True
                    fill_step_fn(page, step)
                    page.wait_for_timeout(100)
                    if (
                        not step.get("filled")
                        and str(step.get("status") or "").strip().casefold() != "skipped_not_found"
                    ):
                        note = str(step.get("note") or "").strip()
                        retry_note = "Retried once and still could not confirm the planned profile-backed value on the live form."
                        if retry_note not in note:
                            step["note"] = f"{note} {retry_note}".strip()

            page_path = page_screenshots_dir / "page_01.png"
            capture_fn(page, page_path)
            if not page_path.exists():
                capture_fn(page, page_path)

            live_required_blockers: list[dict] = []
            if live_required_field_scan_fn is not None:
                live_required_blockers.extend(list(live_required_field_scan_fn(page, steps) or []))

            if post_fill_hook is not None:
                post_fill_hook(page)

            # --- Phase 3: Capture screenshots and write report ---
            pre_submit_path = Path(payload["artifacts"]["pre_submit_screenshot"])
            capture_fn(page, pre_submit_path)
            if not pre_submit_path.exists():
                capture_fn(page, pre_submit_path)
            runtime = {"steps": steps, "pages": [{"page_index": 1, "screenshot": str(page_path)}]}
            report_payload = write_report(payload, board_name=board_name, runtime=runtime)
            blocking_fields = blocking_unconfirmed_report_entries(
                list(report_payload.get("planned_but_unconfirmed_fields") or [])
            )
            blocking_fields.extend(
                [
                    {
                        "field_name": str(question.get("field_name") or "").strip(),
                        "label": str(question.get("label") or question.get("field_name") or "").strip(),
                        "kind": str(question.get("kind") or "").strip(),
                        "source": str(question.get("source") or "live_application_form").strip(),
                        "required": True,
                        "status": str(question.get("status") or "planned").strip() or "planned",
                        "reason": str(question.get("reason") or "").strip()
                        or (
                            "The live application form contains a required question without a deterministic or "
                            "generated answer in the current payload."
                        ),
                        "note": str(question.get("note") or "").strip()
                        or "Required discovered question left unresolved during payload reconciliation.",
                    }
                    for question in list(report_payload.get("unknown_questions") or [])
                    if isinstance(question, dict) and bool(question.get("required"))
                ]
            )
            blocking_fields.extend(live_required_blockers)
            if draft_boundary_scan_fn is not None:
                draft_boundary_blocker = draft_boundary_scan_fn(page)
                if draft_boundary_blocker is not None:
                    blocking_fields.append(draft_boundary_blocker)
            if not pre_submit_path.exists():
                blocking_fields.append(
                    required_artifact_blocker_step(
                        field_name="pre_submit_screenshot",
                        label="Current-attempt pre-submit screenshot",
                        source="autofill_pipeline",
                        artifact_key="pre_submit_screenshot",
                        expected_path=pre_submit_path,
                        note="Retried screenshot capture once, but the pre-submit proof artifact still was not written.",
                        reason="The current submit attempt is missing the required pre-submit screenshot proof.",
                    )
                )

            draft_state = classify_state_fn(page_snapshot_fn(page))
            if draft_state["status"] == "captcha_required":
                clear_pending_user_input(out_dir)
                captcha_message = "Submission skipped: captcha required. Moving on to next job."
                write_submission_result(
                    out_dir=out_dir,
                    status="skipped_captcha",
                    failure_type="skipped_captcha",
                    job_url=str(payload.get("job_url") or payload.get("application_url") or ""),
                    message=captcha_message,
                    board=board_name,
                    provider=str(payload.get("provider") or "").strip() or None,
                    artifacts={
                        "report_json": str(payload["artifacts"]["report_json"]),
                        "report_markdown": str(payload["artifacts"]["report_markdown"]),
                        "pre_submit_screenshot": str(pre_submit_path),
                        "page_screenshots_dir": str(page_screenshots_dir),
                    },
                )
                print(
                    f"{board_title} submission skipped: captcha required. Moving on.",
                    file=sys.stderr,
                )
                return 0

            # --- Phase 4: Check for pending user input ---
            pending_path = write_pending_user_input_for_unconfirmed_fields(
                out_dir,
                board=board_name,
                fields=blocking_fields,
                report_json=payload["artifacts"]["report_json"],
                report_markdown=payload["artifacts"]["report_markdown"],
                pre_submit_screenshot=payload["artifacts"]["pre_submit_screenshot"],
            )
            if pending_path is not None:
                print(
                    f"{board_title} autofill left planned fields unconfirmed. "
                    f"See {pending_path.relative_to(PROJECT_ROOT)} before submitting.",
                    file=sys.stderr,
                )
                if submit:
                    return 1
            else:
                clear_pending_user_input(out_dir)

            if not submit:
                print(f"Filled {board_title} application for review: {pre_submit_path.relative_to(PROJECT_ROOT)}")
                if browser.session_viewer_url:
                    print(f"{board_title} Steel session viewer: {browser.session_viewer_url}")
                return 0

            # Inject observer to capture transient toast/flash messages
            page.evaluate("""() => {
                window.__transientMessages = [];
                const observer = new MutationObserver(mutations => {
                    for (const m of mutations) {
                        for (const node of m.addedNodes) {
                            if (node.nodeType !== 1) continue;
                            const el = node;
                            const text = (el.innerText || '').trim();
                            if (!text || text.length > 500) continue;
                            const style = window.getComputedStyle(el);
                            const bg = style.backgroundColor || '';
                            const role = el.getAttribute('role') || '';
                            const cls = el.className || '';
                            window.__transientMessages.push({
                                text, tag: el.tagName, bg, role, cls: String(cls).slice(0, 200),
                                time: Date.now()
                            });
                        }
                    }
                });
                observer.observe(document.body, {childList: true, subtree: true});
                window.__transientObserver = observer;
            }""")

            submit_started_at_utc: str | None = None
            submit_already_clicked = False

            # --- Phase 5: Pre-submit hook (e.g. Lever hCaptcha wait) ---
            if pre_submit_hook is not None:
                hook_started_at_utc = datetime.now(UTC).replace(microsecond=0).isoformat()
                submit_already_clicked = bool(pre_submit_hook(page))
                if submit_already_clicked:
                    submit_started_at_utc = hook_started_at_utc

            # --- Phase 6: Click submit ---
            if not submit_already_clicked:
                if not click_submit_fn(page):
                    print(f"{board_title} submit buttons were not available after autofill.", file=sys.stderr)
                    return 1
                submit_started_at_utc = datetime.now(UTC).replace(microsecond=0).isoformat()

            assert submit_started_at_utc is not None
            email_watcher = build_email_confirmation_watcher(payload, min_received_at_utc=submit_started_at_utc)

            def _capture_post_submit():
                """Capture a screenshot of the post-submit confirmation page."""
                post_path = payload["artifacts"].get("post_submit_screenshot")
                if not post_path:
                    return
                try:
                    capture_fn(page, Path(post_path))
                except Exception:
                    pass

            def _try_captcha_wait(email_watcher, submit_started_at_utc):
                """Call captcha wait, run downstream actions if confirmed. Returns 0 or None."""
                _wait_fn = _default_captcha_wait
                _wait_result = _wait_fn(
                    page,
                    headless=headless,
                    payload=payload,
                    board_title=board_title,
                    classify_state_fn=classify_state_fn,
                    page_snapshot_fn=page_snapshot_fn,
                    email_watcher=email_watcher,
                    confirmed_outcome_from_email_fn=confirmed_outcome_from_email_fn,
                    capture_fn=capture_fn,
                    submit_started_at_utc=submit_started_at_utc,
                )
                if _wait_result["status"] == "confirmed":
                    _outcome = _wait_result.get("outcome", {})
                    _email_conf = _wait_result.get("email_confirmation")
                    _capture_post_submit()
                    sync_notion_after_submit(
                        payload,
                        _outcome,
                        provider=board_name,
                        email_confirmation=_email_conf,
                        min_received_at_utc=submit_started_at_utc,
                    )
                    reply_to_confirmation_email(
                        payload,
                        board_name=board_name,
                        email_confirmation=_email_conf,
                    )
                    return 0
                return None

            # --- Phase 7: Poll for confirmation ---
            last_snapshot = None
            _max_polls = 30 * (1 + MAX_VALIDATION_RETRIES)
            for _ in range(_max_polls):
                page.wait_for_timeout(500)
                last_snapshot = page_snapshot_fn(page)
                # Check email confirmation
                email_confirmation = email_watcher.poll()
                if email_confirmation and confirmed_outcome_from_email_fn:
                    outcome = confirmed_outcome_from_email_fn(last_snapshot, email_confirmation)
                    _capture_post_submit()
                    sync_notion_after_submit(
                        payload,
                        outcome,
                        provider=board_name,
                        email_confirmation=email_confirmation,
                        min_received_at_utc=submit_started_at_utc,
                    )
                    reply_to_confirmation_email(payload, board_name=board_name, email_confirmation=email_confirmation)
                    return 0
                # Check page state
                state = classify_state_fn(last_snapshot)
                if state["status"] == "confirmed":
                    outcome = {"status": "confirmed", "reason": state.get("reason"), "snapshot": last_snapshot}
                    _capture_post_submit()
                    sync_notion_after_submit(
                        payload, outcome, provider=board_name, min_received_at_utc=submit_started_at_utc
                    )
                    reply_to_confirmation_email(payload, board_name=board_name)
                    return 0
                if state["status"] == "captcha_required":
                    _rc = _try_captcha_wait(email_watcher, submit_started_at_utc)
                    if _rc is not None:
                        return _rc
                    break
                if state["status"] == "validation_error":
                    # Don't break immediately — the form may transition to a
                    # success page after a transient validation flash.  Wait a
                    # bit and re-check once before giving up.
                    page.wait_for_timeout(2000)
                    last_snapshot = page_snapshot_fn(page)
                    state = classify_state_fn(last_snapshot)
                    if state["status"] == "confirmed":
                        outcome = {"status": "confirmed", "reason": state.get("reason"), "snapshot": last_snapshot}
                        _capture_post_submit()
                        sync_notion_after_submit(
                            payload, outcome, provider=board_name, min_received_at_utc=submit_started_at_utc
                        )
                        reply_to_confirmation_email(payload, board_name=board_name)
                        return 0
                    # Retry: re-fill all form fields (validation errors
                    # often clear file uploads) and re-submit.
                    _validation_retries = getattr(_try_captcha_wait, "_val_retries", 0)
                    if _validation_retries < MAX_VALIDATION_RETRIES:
                        _try_captcha_wait._val_retries = _validation_retries + 1
                        _errors = state.get("errors", [])
                        print(
                            f"{board_title} validation error (attempt {_validation_retries + 1}/"
                            f"{MAX_VALIDATION_RETRIES}): {_errors}. Re-filling fields and retrying.",
                            file=sys.stderr,
                        )
                        page.wait_for_timeout(1000)
                        for step in steps:
                            try:
                                fill_step_fn(page, step)
                                page.wait_for_timeout(100)
                            except Exception:
                                pass
                        page.wait_for_timeout(500)
                        if click_submit_fn(page):
                            submit_started_at_utc = datetime.now(UTC).replace(microsecond=0).isoformat()
                            email_watcher = build_email_confirmation_watcher(
                                payload,
                                min_received_at_utc=submit_started_at_utc,
                            )
                            continue  # re-enter polling loop
                    break

            # --- Phase 8: Final email check and debug artifacts ---
            email_confirmation = email_watcher.poll(force=True)
            if email_confirmation and confirmed_outcome_from_email_fn:
                outcome = confirmed_outcome_from_email_fn(last_snapshot, email_confirmation)
                sync_notion_after_submit(
                    payload,
                    outcome,
                    provider=board_name,
                    email_confirmation=email_confirmation,
                    min_received_at_utc=submit_started_at_utc,
                )
                reply_to_confirmation_email(payload, board_name=board_name, email_confirmation=email_confirmation)
                return 0

            # Capture transient messages before taking debug snapshot
            try:
                _transient = page.evaluate("() => window.__transientMessages || []")
                if _transient:
                    print(f"{board_title} transient messages captured:", flush=True)
                    for msg in _transient:
                        print(
                            f"  [{msg.get('tag')}] {msg.get('text')!r} (bg={msg.get('bg')}, role={msg.get('role')}, cls={msg.get('cls', '')[:80]})",
                            flush=True,
                        )
            except Exception:
                pass

            debug_html = Path(payload["artifacts"]["submit_debug_html"])
            debug_png = Path(payload["artifacts"]["submit_debug_screenshot"])
            debug_html.write_text(page.content(), encoding="utf-8")
            capture_fn(page, debug_png)
            # Always take a fresh snapshot — the page may have navigated
            # since the last snapshot was captured in the polling loop.
            snapshot = page_snapshot_fn(page)
            state = classify_state_fn(snapshot)
            if state["status"] == "captcha_required":
                _rc = _try_captcha_wait(email_watcher, submit_started_at_utc)
                if _rc is not None:
                    return _rc
                print(
                    f"{board_title} submission skipped: captcha required. Moving on.",
                    file=sys.stderr,
                )
                return CAPTCHA_SKIP_EXIT_CODE
            print(
                f"{board_title} submit did not reach a confirmed completion state: {state['status']}. "
                f"See {debug_html.relative_to(PROJECT_ROOT)} and {debug_png.relative_to(PROJECT_ROOT)}.",
                file=sys.stderr,
            )
            return 1
        finally:
            browser.close()
